### ISSUE TITLE
Creating report fails when at least one of the PRs was closed as part of triage

### ISSUE THREAD

**Issue by anden3** [KittyBorgX/triage-cli#2]
```
Traceback (most recent call last):
  File "/home/andre/downloads/triage-cli/src/main.py", line 42, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/andre/downloads/triage-cli/src/main.py", line 30, in main
    sorted_pull_requests = doc.get_sorted_pull_requests()
  File "/home/andre/downloads/triage-cli/src/docwrite.py", line 21, in get_sorted_pull_requests
    sorted_reviewers = sorted(self.sorted_pull_requests.keys())
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by anden3** [comment]
This was the PR in question: https://github.com/rust-lang/rust/pull/108631
